src/styles/components/css/main.css

tbl_globel css

---

package-lock.json
package.json
src/App.js
src/components/layout/sidenav/ceosidenav.component.jsx
src/pages/ceoFlow/Dashboard/ProjectsIssuesChart.jsx
src/pages/ceoFlow/Dashboard/index1.jsx
src/pages/ceoFlow/KanbanBoard/index.jsx
src/pages/ceoFlow/Project/CreateProject.jsx
src/pages/ceoFlow/Project/ProjectDeatils.jsx
src/pages/ceoFlow/Project/ProjectMilestoneTable.jsx
src/pages/ceoFlow/Project/ProjectProgressBar.js
src/pages/ceoFlow/Project/ProjectSummary.jsx
src/pages/ceoFlow/Project/index.jsx
src/styles/components/css/aqsStyles/aqsboqopen.css
src/styles/components/css/aqsStyles/aqsvendorpricedetails.css
src/styles/components/css/ceoStyles/ceocreateproject.css
src/styles/components/css/ceoStyles/ceodashboard.css
src/styles/components/css/engineerStyles/engineermaterialview.css
src/styles/components/css/main.css
src/styles/index.css

28 March First Version

---

package-lock.json
package.json
src/App.js
src/pages/aqsFlow/KanbanBoard/index.jsx
src/pages/mdflow/KanbanBoard/TicketDetails.jsx
src/pages/mdflow/Project/ProjectDeatils.jsx
src/pages/mdflow/Project/ProjectMilestoneTable.jsx
src/styles/components/css/aqsStyles/aqsboqmain.css
src/styles/components/css/engineerStyles/engineerreportcreate.css
src/styles/components/css/home.css
src/styles/index.css

Reverts ccssadmin/buildflow#25

Revert "Small changes"

---

src/pages/ceoFlow/Reports/index.jsx
src/styles/components/css/ceoStyles/reports.css

.ceo-report  .report-container add parent name

.ceo-report  .report-container add parent name

---

src/App.js
src/components/layout/sidenav/ceosidenav.component.jsx
src/components/layout/sidenav/financesidennav.component.jsx
src/pages/ceoFlow/Reports/ViewReport.jsx
src/pages/ceoFlow/Reports/index.jsx
src/pages/ceoFlow/Resources/civilWorkerList.jsx
src/pages/financeFlow/Reports/ReportCreate.jsx
src/pages/financeFlow/Reports/index.jsx
src/styles/components/css/ceoStyles/ceofinance.css
src/styles/components/css/ceoStyles/civilworkers.css
src/styles/components/css/ceoStyles/reports.css
src/styles/components/css/ceoStyles/resources.css

Side Nav Active and Guna Code

---

src/constant/service.js
src/hooks/Ceo/useRoleBasedEmp.js
src/hooks/Ceo/useTicket.js
src/pages/Login/Login.jsx
src/pages/ceoFlow/Project/BudgetFinancialAllocation.jsx
src/pages/ceoFlow/Project/CreateProject.jsx
src/pages/ceoFlow/Project/ProjectTeamStakeholder.jsx
src/pages/ceoFlow/Project/TimelineMilestonePlanning.jsx
src/services/index.js
src/store/actions/Ceo/RoleBasedEmpAction.js
src/store/actions/Ceo/TicketCreate.js
src/store/selector/ceo/ticketSelector.js
src/store/slice/Ceo/RoleBasedEmpSlice.js
src/store/slice/Ceo/TicketcreationSlicer.js
src/styles/components/css/login.css

updated with  ticket

---

src/App.js
src/constant/service.js
src/hooks/Ceo/useCeoProject.js
src/pages/ceoFlow/Project/CreateProject.jsx
src/pages/ceoFlow/Project/ProjectDeatils.jsx
src/pages/ceoFlow/Project/ProjectMilestoneTable.jsx
src/pages/ceoFlow/Project/ProjectSummary.jsx
src/pages/ceoFlow/Project/ProjectTeamStakeholder.jsx
src/pages/ceoFlow/Project/RiskComplianceAssessment.jsx
src/pages/ceoFlow/Project/index.jsx
src/services/index.js
src/store/actions/Ceo/ceoprojectAction.js
src/store/selector/ceo/ceoProjectSelector.js
src/store/slice/Ceo/ceoprojectSlicer.js

Kamesh code project list and deatils

Kamesh code project list and deatils

---

src/components/common/NotificationTab.jsx
src/constant/service.js
src/hooks/Ceo/useNotification.js
src/pages/aqsFlow/KanbanBoard/index.jsx
src/pages/ceoFlow/Project/BudgetFinancialAllocation.jsx
src/pages/ceoFlow/Project/CreateProject.jsx
src/pages/ceoFlow/Project/ProjectSummary.jsx
src/pages/ceoFlow/Project/TimelineMilestonePlanning.jsx
src/pages/mdflow/KanbanBoard/Kanban.jsx
src/pages/pmFlow/KanbanBoard/index.jsx
src/services/index.js
src/store/actions/Ceo/createNotification.js
src/store/root-reducer.js
src/store/selector/ceo/notificationSelector.js
src/store/slice/Ceo/notificationSlicer.js
src/styles/components/css/ceoStyles/ceocreateproject.css

Keerthana Code

---

src/components/common/ProjectEmployeesList.jsx
src/constant/service.js
src/hooks/Ceo/useCeoProject.js
src/pages/ceoFlow/Project/ProjectDeatils.jsx
src/pages/ceoFlow/Project/ProjectMilestoneTable.jsx
src/pages/ceoFlow/Project/ProjectProgressBar.jsx
src/pages/ceoFlow/Project/RiskComplianceAssessment.jsx
src/pages/ceoFlow/Project/index.jsx
src/pages/mdflow/KanbanBoard/Kanban.jsx
src/pages/pmFlow/Project/ProjectMilestoneTable.jsx
src/pages/pmFlow/Project/index.jsx
src/services/index.js
src/store/actions/Ceo/ceoprojectAction.js
src/store/root-reducer.js
src/store/slice/Ceo/auth.js
src/store/slice/Ceo/ceoprojectSlicer.js
src/store/slice/Ceo/riskSlice.js

Kamesh Code And Guna Code

---

src/pages/mdflow/Project/Project.jsx
src/pages/mdflow/Project/ProjectDeatils.jsx
src/pages/mdflow/Project/ProjectMilestoneTable.jsx

ProjectList and ProjectDetails with milestoneDetails and EmployeeDetails

mdflow_ProjectList&ProjectDetails

---

src/constant/service.js
src/pages/mdflow/KanbanBoard/Kanban.jsx
src/services/index.js
src/store/actions/kanbanAction.js
src/store/actions/masterAction.js
src/store/selector/masterSelector.js
src/store/slice/master.js

Subash dev

---

src/App.js
src/pages/purchasemanagerFlow/Dashboard/index.jsx
src/pages/purchasemanagerFlow/KanbanBoard/index.jsx
src/pages/purchasemanagerFlow/Po/index.jsx
src/pages/purchasemanagerFlow/Po/purchaseOrder.jsx
src/pages/purchasemanagerFlow/Vendors/VendorDetails.jsx
src/pages/purchasemanagerFlow/Vendors/index.jsx

Guna Code Purchase Manager Flow

Guna Code Purchase Manager Flow

---

src/App.js
src/pages/ceoFlow/KanbanBoard/index.jsx
src/pages/ceoFlow/Project/BudgetFinancialAllocation.jsx
src/pages/pmFlow/Dashboard/BudgetUsageProgressBar.js
src/pages/pmFlow/Dashboard/index.jsx
src/styles/components/css/aqsStyles/aqscostestimation.css
src/styles/components/css/ceoStyles/ceocreateproject.css
src/styles/components/css/main.css
src/styles/components/css/pmStyles/dashboard.css

PM Dashboard

---

src/pages/aqsFlow/KanbanBoard/index.jsx
src/pages/ceoFlow/Project/ProjectProgressBar.jsx
src/pages/engineerFlow/KanbanBoard/index.jsx
src/pages/financeFlow/KanbanBoard/index.jsx
src/pages/hrFlow/KanbanBoard/index.jsx
src/pages/mdflow/Project/ProjectProgressBar.js
src/pages/pmFlow/Project/ProjectProgressBar.jsx
src/pages/purchasemanagerFlow/KanbanBoard/index.jsx
src/pages/vendorFlow/KanbanBoard/index.jsx
src/styles/components/css/main.css

Kanban All Pages

---

src/pages/ceoFlow/KanbanBoard/index.jsx

ceo kanban

---

src/App.js
src/pages/financeFlow/KanbanBoard/TicketDetails.jsx
src/pages/financeFlow/KanbanBoard/index.jsx

Finanice ticket details page and app js file role number change

Finanice ticket details page and app js file role number change

---

src/pages/engineerFlow/Material/MaterialCreateScreen.jsx
src/store/actions/Engineer/upsertboqaction.js
src/store/actions/hr/designationaction.js
src/store/actions/vendor/getvendoraction.js
src/store/root-reducer.js
src/store/slice/Engineer/upsertboqslice.js
src/store/slice/Vendor/getvendorslice.js
src/store/slice/hr/designationslice.js

Create BOQ Sakthi Code

---

src/pages/hrFlow/Employee/AddEmployee.jsx
src/pages/hrFlow/Employee/index.jsx
src/styles/components/css/hr/hrms.css

Sakthi HRMS

---

src/pages/engineerFlow/Material/MaterialCreateScreen.jsx
src/pages/hrFlow/Employee/AddEmployee.jsx
src/store/actions/Engineer/upsertboqaction.js
src/store/slice/Engineer/upsertboqslice.js
src/styles/components/css/hr/hrms.css

BOQ ID Get Sakthi Code

---

src/App.js

purchasemanager

---

src/pages/aqsFlow/KanbanBoard/index.jsx
src/pages/ceoFlow/KanbanBoard/index.jsx
src/pages/engineerFlow/KanbanBoard/index.jsx
src/pages/financeFlow/KanbanBoard/index.jsx
src/pages/hrFlow/KanbanBoard/index.jsx
src/pages/mdflow/KanbanBoard/Kanban.jsx
src/pages/pmFlow/KanbanBoard/index.jsx
src/pages/purchasemanagerFlow/KanbanBoard/index.jsx

TicketDetails Page Commen

---

src/components/common/MaterialViewScreen.jsx
src/pages/engineerFlow/Material/MaterialCreateScreen.jsx

Thangarasu dev new

---

src/pages/purchasemanagerFlow/Po/index.jsx
src/pages/vendorFlow/Po/EditPurchaseOrder.jsx

hi subash this is purhcase magaer flow po get

Purchase order Get

---

src/pages/purchasemanagerFlow/Po/PoCreateAutoGenrate.jsx
src/pages/purchasemanagerFlow/Po/purchaseOrderCreate.jsx

purchaseorder Ticket navigation,manual and auto

purchaseorder Ticket navigation,manual and auto

---

src/components/common/NotificationTab.jsx
src/pages/aqsFlow/Materials/NotificationTab.jsx
src/pages/pmFlow/Material/NotificationTab.jsx

while select the notification card it redirect to ticket details page for all flow

redirect to ticket detail page

---

src/App.js
src/pages/Login/Login.jsx
src/pages/Login/SessionExpiredModel.jsx
src/pages/hrFlow/Employee/AddEmployee.jsx
src/pages/hrFlow/Employee/index.jsx
src/services/api.js
src/styles/components/css/hr/hrms.css
src/utils/storage.js

add the code for refresh token and fix some bugs on hr flow

fixed refresh token

---

src/App.js
src/pages/aqsFlow/Settings/General.jsx
src/pages/ceoFlow/Settings/General.jsx
src/pages/engineerFlow/Settings/General.jsx
src/pages/financeFlow/Settings/General.jsx
src/pages/hrFlow/Settings/General.jsx
src/pages/mdflow/Settings/General.jsx
src/pages/pmFlow/Settings/General.jsx
src/pages/purchasemanagerFlow/Settings/General.jsx
src/pages/vendorFlow/Settings/General.jsx

fixed logout issue and while entering the wrong credentials it show the session exipred modal now i fixed that too

fixed logout issue and wrong credentials issue

---

src/pages/ceoFlow/Reports/index.jsx
src/pages/engineerFlow/Report/ReportCreateScreen.jsx
src/store/actions/report/ceoreportaction.js
src/store/actions/report/reportcreateaction.js
src/store/slice/report/ceoreportslice.js
src/store/slice/report/reportslice.js

Kamesh Report File Upload code

Kamesh Report File Upload code

---

src/pages/pmFlow/Dashboard/index.jsx
src/pages/pmFlow/Resources/index.jsx
src/pages/pmFlow/Task/index.jsx
src/styles/components/css/main.css

bug fixed on project manager flow

Projectmanager bug fix

---

src/components/common/ProjectSummary.jsx
src/hooks/Ceo/useCeoProject.js
src/pages/ceoFlow/Project/BudgetFinancialAllocation.jsx
src/pages/ceoFlow/Project/CreateProject.jsx
src/pages/ceoFlow/Project/ProjectBasicDetails.jsx
src/pages/ceoFlow/Project/ProjectMilestoneTable.jsx
src/pages/ceoFlow/Project/ProjectTeamStakeholder.jsx
src/pages/ceoFlow/Project/RiskComplianceAssessment.jsx
src/pages/ceoFlow/Project/TimelineMilestonePlanning.jsx
src/pages/ceoFlow/Project/index.jsx
src/store/actions/Ceo/ceoprojectAction.js

Guna Create Project and Edit Project and Delete Project

Guna Create Project and Edit Project and Delete Project

---

src/App.js
src/pages/hrFlow/Employee/AddEmployee.jsx

after expires modal appear click the logout the modal doesn't close but now i fixed that

logout bug

---

src/pages/engineerFlow/Material/MaterialCreateScreen.jsx
src/pages/vendorFlow/Po/index.jsx
src/store/actions/Engineer/upsertboqaction.js
src/store/slice/Engineer/upsertboqslice.js

boq functionlity project id based rolename
